plugins {
    id 'java'
    id 'application'
}

application {
    mainClass = 'Main'
}

group = 'com.esdc'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation "org.springframework:spring-webmvc:${rootProject.ext.springVersion}"
    implementation "org.springframework:spring-context:${rootProject.ext.springVersion}"
    implementation "com.fasterxml.jackson.core:jackson-databind:${rootProject.ext.jacksonVersion}"
    implementation "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:${rootProject.ext.jacksonVersion}"
    implementation "jakarta.servlet:jakarta.servlet-api:${rootProject.ext.jakartaVersion}"
    implementation "org.apache.tomcat.embed:tomcat-embed-core:${rootProject.ext.tomcatEmbedVersion}"
    implementation "org.apache.tomcat.embed:tomcat-embed-el:${rootProject.ext.tomcatEmbedVersion}"
    implementation "jakarta.validation:jakarta.validation-api:${rootProject.ext.jakartaValidationVersion}"
    implementation "org.hibernate.validator:hibernate-validator:${rootProject.ext.hibernateValidatorVersion}"
    implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui:${rootProject.ext.springdocVersion}"
    compileOnly "org.projectlombok:lombok:${rootProject.ext.lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${rootProject.ext.lombokVersion}"
    implementation "org.slf4j:slf4j-api:${rootProject.ext.slf4jVersion}"
    implementation "ch.qos.logback:logback-classic:${rootProject.ext.logbackVersion}"
}

compileJava {
    options.compilerArgs << '-parameters'
}

test {
    useJUnitPlatform()
}
