spring:
  application:
    name: lab3
  datasource:
    url: jdbc:postgresql://localhost:5432/lab3
    username: lab3
    password: lab3
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: lab3 pool
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  profiles:
    active: jpa-repo #jpa #jpa-repo

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html


