version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: cofee-postgres
    environment:
      POSTGRES_DB: coffeedb
      POSTGRES_USER: coffeeuser
      POSTGRES_PASSWORD: coffeepass
    ports:
      - "5437:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U examuser -d examdb"]
      interval: 10s
      timeout: 5s
      retries: 5


