services:
  postgres:
    image: postgres:18
    container_name: fp_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pg_booking:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:4-management
    container_name: fp_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rb_storage:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  booking-service:
    build:
      context: ..
      dockerfile: FinalProject/booking-service/Dockerfile
    container_name: fp_booking
    environment:
      DB_HOST: postgres
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      RABBITMQ_HOST: rabbitmq
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  payment-service:
    build:
      context: ..
      dockerfile: FinalProject/payment-service/Dockerfile
    container_name: fp_payment
    environment:
      RABBITMQ_HOST: rabbitmq
    ports:
      - "8083:8083"
    depends_on:
      rabbitmq:
        condition: service_healthy

  notification-service:
    build:
      context: ..
      dockerfile: FinalProject/notification-service/Dockerfile
    container_name: fp_notification
    environment:
      RABBITMQ_HOST: rabbitmq
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN:-}
    ports:
      - "8081:8081"
    depends_on:
      rabbitmq:
        condition: service_healthy

  audit-service:
    build:
      context: ..
      dockerfile: FinalProject/audit-service/Dockerfile
    container_name: fp_audit
    environment:
      DB_HOST: postgres
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      RABBITMQ_HOST: rabbitmq
    ports:
      - "8082:8082"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

volumes:
  pg_booking:
  rb_storage:
