server.port=8080
server.host=localhost
jwt.secret.access=kjdlgjsljjjskljlskfj;jhkjsjehsehkjehkjhhhhfdhdjfhjdfhkhdfh
jwt.secret.refresh=hjhsfhgkhsh7suehwkhkjsdbbjxjnnweuh;ajbsjautuxhnrjfzuh
#hours
jwt.lifetime.access=1
#days
jwt.lifetime.refresh=7